### ISSUE TITLE
Search autocomplete slow, hangs

### ISSUE THREAD

**Issue by edbond** [cljsjs/cljsjs.github.io#11]
http://cljsjs.github.io/
Started to type 'cod' for 'codemirror'
Chrome 52.0.2743.116 (64-bit), mac

See timeline image, keyup took 13sec to filter:
![2016-08-19_16-41-23](https://cloud.githubusercontent.com/assets/1044/17811643/4ff40fd2-662c-11e6-95bc-9a9c8eb6ba96.png)

**Comment by edbond** [comment]
Some ideas to implement:
- start filter only when > 2 chars input
- limit number of results to 10 and display "and 30 more"
- debounce input - start filtering only when user stops typing

**Comment by Deraen** [comment]
Should be fixed now: http://cljsjs.github.io/
