### ISSUE TITLE
Allow filtering by package type

### ISSUE THREAD

**Issue by martinklepsch** [cljsjs/cljsjs.github.io#16]
Package types: Foreign dep, Closure lib, CommonJS/AMD/ES6 (forthcoming)

**Comment by Deraen** [comment]
![image](https://cloud.githubusercontent.com/assets/648087/18555669/5586f09a-7b71-11e6-9c33-e3361d60d5af.png)

Implemented with descriptions for each package type. Could use spellcheck & style tuning.
