### ISSUE TITLE
Material UI package link doesn't go to proper latest version

### ISSUE THREAD

**Issue by dijonkitchen** [cljsjs/cljsjs.github.io#21]
On http://cljsjs.github.io/ , it goes here: https://github.com/cljsjs/packages/tree/master/material-ui

Instead of here: https://github.com/cljsjs/packages/tree/master/material-ui_1

**Comment by dijonkitchen** [comment]
@Deraen any way you can fix this?

**Comment by Deraen** [comment]
Easiest solution was to rename the folders, so the folder without version number is the latest. Done now.

**Comment by dijonkitchen** [comment]
Thanks!
