### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by fdserr** [cljsjs/cljsjs.github.io#5]
Top of the homepage: "[...] concentrate packaging efforts to make everyone’s live a little easier."
Shouldn't it read "[...] make everyone's li**f**e a little easier." ?
Keep-up the good job, thankies!

**Comment by Deraen** [comment]
Fixed https://github.com/cljsjs/cljsjs.github.io/commit/39b0770b535f0bed25198ba2d2f74e8dafbbd4c4.
