### ISSUE TITLE
react-input-mask homepage points to the wrong place

### ISSUE THREAD

**Issue by futuro** [cljsjs/cljsjs.github.io#9]
The homepage link for react-input mask points to http://https//github.com/sanniassin/react-input-mask instead of https://github.com/sanniassin/react-input-mask, which can be verified on [line 1081 of packages.html](https://github.com/cljsjs/cljsjs.github.io/blob/master/_includes/packages.html#L108).

**Comment by Deraen** [comment]
Seems to fixed.
